// Generated by Wrangler on Sun Sep 08 2024 10:42:41 GMT-0400 (Eastern Daylight Time)
// by running `wrangler types --env-interface CloudflareEnv env.d.ts`

interface CloudflareEnv {
	DATABASE: D1Database;
}
