name = "ignored_ai"
compatibility_date = "2024-09-07"
compatibility_flags = [ "nodejs_compat" ]
pages_build_output_dir = ".vercel/output/static"

[[d1_databases]]
binding = "DATABASE"
database_name = "dev-d1-ignored-ai" 
database_id = "789c1b3a-2c35-4971-8bf4-d3f0102e3289"

[[env.production.d1_databases]]
binding = "DATABASE"
database_name = "prod-d1-ignored-ai"
database_id = "dc1cc02a-2b06-4018-888a-0447e4b30584"
